server:
  port: 8082

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  config:
    activate:
      on-profile: default
  application:
    name: pizza
    zipkin: http://zipkin:9411
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5433/pizza_db
    username: postgres
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher